"""Truing up constraints

Revision ID: 433824de33a5
Revises: b2e9c078f4ec
Create Date: 2023-12-08 22:19:04.279691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433824de33a5'
down_revision: Union[str, None] = 'b2e9c078f4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_unique_constraint("Email", ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("Email", type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    # ### end Alembic commands ###
