"""Updating field name to timstamp on user history

Revision ID: 53897f432f4a
Revises: 81d8dca6dbbf
Create Date: 2023-12-09 11:05:14.369213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53897f432f4a'
down_revision: Union[str, None] = '81d8dca6dbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.INTEGER(), nullable=False))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
