"""Adding authentication log table

Revision ID: 7b8986738c92
Revises: 064196be8260
Create Date: 2023-12-09 10:12:00.450840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8986738c92'
down_revision: Union[str, None] = '064196be8260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authentication_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authentication_log_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authentication_log_id'))

    op.drop_table('authentication_log')
    # ### end Alembic commands ###
