"""Updating failure_reason to ENUM instead of string

Revision ID: 8903104b6f2a
Revises: 53897f432f4a
Create Date: 2023-12-09 11:45:56.475329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8903104b6f2a'
down_revision: Union[str, None] = '53897f432f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_reason', sa.Enum('Bad password', 'Bad username', 'Bad IP', 'Bad user agent', 'Bad 2FA', name='failurereason'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_log', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')

    # ### end Alembic commands ###
