[lint]
select = ["E4", "E7", "E9", "F", "ANN", "E", "W", "C90", "I", "N", "D", "ASYNC"]
ignore-init-module-imports = true
preview = true 

[format]
indent-style = "tab"
preview = true 

[lint.mccabe]
max-complexity = 2 

[lint.isort]
force-single-line = true
lines-between-types = 1
